/**
 * Service for managing qualifications in the database
 * @since 2026-03-03
 * @author Michael Townsend <@continuities>
 */

import pool from '@/db';
import { PoolClient } from 'pg';
import { cache } from 'react';

const rowToQualification = (row: any): QualificationInfo => ({
  id: row.id,
  eventId: row.eventId,
  teamId: row.teamId,
  name: row.name,
  errorMessage: row.errorMessage
});

/**
 * Fetches a list of qualifications associated with a specific event.
 * @param eventId - The ID of the event to fetch qualifications for
 * @returns A list of qualifications associated with the specified event
 */
export const getQualificationsForEvent = cache(
  async (eventId: EventId): Promise<QualificationInfo[]> => {
    console.info(`Fetching qualifications for event ${eventId}`);
    const res = await pool.query(
      `
        SELECT
          "id",
          "eventId",
          "teamId",
          "name",
          "errorMessage"
        FROM qualification
        WHERE "eventId" = $1
     `,
      [eventId]
    );
    return res.rows.map(rowToQualification);
  }
);

/**
 * Fetches a list of qualifications associated with specific events.
 * @param eventIds - List of EventIds to fetch qualifications for
 * @returns A list of qualifications associated with the specified events
 */
export const getQualificationsForEvents = cache(
  async (eventIds: EventId[]): Promise<QualificationInfo[]> => {
    console.info(`Fetching qualifications for events ${eventIds.toString()}`);
    if (eventIds.length === 0) {
      return [];
    }
    const res = await pool.query(
      `
        SELECT
          "id",
          "eventId",
          "teamId",
          "name",
          "errorMessage"
        FROM qualification
        WHERE "eventId" = ANY($1)
     `,
      [eventIds]
    );
    return res.rows.map(rowToQualification);
  }
);

/**
 * Fetches a list of qualifications associated with specific teams
 * @param teamIds - List of TeamIds to fetch qualifications for
 * @returns A list of qualifications associated with the specified teams
 */
export const getQualificationsForTeams = cache(
  async (teamIds: TeamId[]): Promise<QualificationInfo[]> => {
    console.info(`Fetching qualifications for teams ${teamIds.toString()}`);
    const res = await pool.query(
      `
        SELECT
          "id",
          "eventId",
          "teamId",
          "name",
          "errorMessage"
        FROM qualification
        WHERE "teamId" = ANY($1)
     `,
      [teamIds]
    );
    return res.rows.map(rowToQualification);
  }
);

/**
 * Fetches a qualification by its ID.
 * @param qualificationId - The ID of the qualification to fetch
 * @returns The qualification information if found, or null if not found
 */
export const getQualificationById = cache(
  async (qualificationId: QualificationId): Promise<QualificationInfo | null> => {
    console.info(`Fetching qualification with id ${qualificationId}`);
    const res = await pool.query(
      `
        SELECT
          "id",
          "eventId",
          "teamId",
          "name",
          "errorMessage"
        FROM qualification
        WHERE id = $1
     `,
      [qualificationId]
    );
    if (res.rowCount === 0) {
      return null;
    }
    return rowToQualification(res.rows[0]);
  }
);

/**
 * Fetches a list of event qualifications assigned to a specific user.
 * @param userId - The ID of the user to fetch qualifications for
 * @param eventId - The ID of the event to filter qualifications by
 * @returns A list of qualifications assigned to the specified user
 */
export const getQualificationsForUser = cache(
  async (userId: UserId, eventId: EventId): Promise<QualificationInfo[]> => {
    console.info(`Fetching qualifications for user ${userId}`);
    const res = await pool.query(
      `
        SELECT
          q."id",
          q."eventId",
          q."teamId",
          q."name",
          q."errorMessage"
        FROM qualification q
        JOIN "user_qualification" uq ON q.id = uq."qualificationId"
        WHERE uq."userId" = $1 AND q."eventId" = $2
     `,
      [userId, eventId]
    );
    return res.rows.map(rowToQualification);
  }
);

/**
 * Creates a new qualification in the database.
 * @param qual - The qualification information to create, excluding the ID which will be generated by the database
 * @param client - Optional database client to use for the transaction
 * @returns The created qualification information, including the generated ID
 */
export const createQualification = async (
  qual: Omit<QualificationInfo, 'id'>,
  client?: PoolClient
): Promise<QualificationInfo> => {
  console.info('Creating qualification with data:', qual);
  const db = client || pool;
  const res = await db.query(
    `
      INSERT INTO qualification (
        "eventId",
        "teamId",
        "name",
        "errorMessage"
      )
      VALUES ($1, $2, $3, $4)
      RETURNING
        "id",
        "eventId",
        "teamId",
        "name",
        "errorMessage"
    `,
    [qual.eventId, qual.teamId, qual.name, qual.errorMessage]
  );
  return rowToQualification(res.rows[0]);
};

/**
 * Updates an existing qualification in the database.
 * @param qualification - The updated qualification information
 * @param client - Optional database client to use for the transaction
 * @returns The updated qualification information after saving to the database
 */
export const updateQualification = async (
  qualification: QualificationInfo,
  client?: PoolClient
): Promise<QualificationInfo> => {
  console.info(`Updating qualification ${qualification.id} with data:`, qualification);
  const db = client || pool;
  const res = await db.query(
    `
      UPDATE qualification
      SET
        "eventId" = $1,
        "teamId" = $2,
        "name" = $3,
        "errorMessage" = $4
      WHERE id = $5
      RETURNING
        "id",
        "eventId",
        "teamId",
        "name",
        "errorMessage"
    `,
    [
      qualification.eventId,
      qualification.teamId,
      qualification.name,
      qualification.errorMessage,
      qualification.id
    ]
  );
  return rowToQualification(res.rows[0]);
};

/**
 * Deletes a qualification from the database.
 * @param qualificationId - The ID of the qualification to delete
 * @param client - Optional database client to use for the transaction
 * @returns A promise that resolves when the deletion is complete
 */
export const deleteQualification = async (
  qualificationId: QualificationId,
  client?: PoolClient
): Promise<void> => {
  console.info(`Deleting qualification with id ${qualificationId}`);
  const db = client || pool;
  await db.query('DELETE FROM qualification WHERE id = $1', [qualificationId]);

  // Shift requirement removal handled by DELETE CASCADE
  // User Qualification removal handled by DELETE CASCADE
};

/**
 * Assigns a qualification to multiple users in the database.
 * @param qualificationId - The ID of the qualification to assign
 * @param userIds - The IDs of the users to assign the qualification to
 * @param client - Optional database client to use for the transaction
 * @returns A promise that resolves when the assignment is complete
 */
export const assignQualificationToUsers = async (
  qualificationId: QualificationId,
  userIds: UserId[],
  client?: PoolClient
): Promise<void> => {
  console.info(`Assigning qualification ${qualificationId} to users ${userIds.toString()}`);
  if (userIds.length === 0) {
    return;
  }
  const db = client || pool;
  const placeholders = userIds
    .map((_, index) => {
      const base = index * 2;
      return `($${base + 1}, $${base + 2})`;
    })
    .join(', ');
  const params = userIds.flatMap((userId) => [userId, qualificationId]);
  await db.query(
    `
      INSERT INTO "user_qualification" ("userId", "qualificationId")
      VALUES ${placeholders}
      ON CONFLICT ("userId", "qualificationId") DO NOTHING
    `,
    params
  );
};

/**
 * Removes a qualification assignment from a user in the database.
 * @param qualificationId - The ID of the qualification to remove
 * @param userId - The ID of the user to remove the qualification from
 * @param client - Optional database client to use for the transaction
 * @returns A promise that resolves when the removal is complete
 */
export const removeQualificationFromUser = async (
  qualificationId: QualificationId,
  userId: UserId,
  client?: PoolClient
): Promise<void> => {
  console.info(`Removing qualification ${qualificationId} from user ${userId}`);
  const db = client || pool;
  await db.query(
    `
      DELETE FROM "user_qualification"
      WHERE "userId" = $1 AND "qualificationId" = $2
    `,
    [userId, qualificationId]
  );
};
