services:
  # Main Next.js application service, for production only
  volunteer-next:
    build:
      context: .
      dockerfile: Dockerfile

    image: volunteer-next:latest
    container_name: volunteer-next
    secrets:
      - env_production
    environment:
      NODE_ENV: production
      PORT: '3000'
    ports:
      - '3000:3000'
    restart: unless-stopped

secrets:
  env_production:
    file: .env.production
