services:
  # Postgres service with pg_cron extension
  db:
    build:
      context: ./db/docker
      dockerfile: Dockerfile
    restart: always
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Liquibase service to run database migrations
  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./db/changelog.xml:/liquibase/changelog.xml
      - ./db/scripts:/liquibase/scripts
      - ./db/drivers:/liquibase/lib
    command: >
      --classpath=/liquibase/lib/postgresql.jar
      --url=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      --changeLogFile=changelog.xml
      --username=postgres
      --password=${POSTGRES_PASSWORD}
      update
    depends_on:
      - db

  # Main Next.js application service, for production only
  volunteer-next:
    build:
      context: .
      dockerfile: Dockerfile
    image: volunteer-next:latest
    container_name: volunteer-next
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: '3000'
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - db

volumes:
  pgdata:
